#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plant_manage?serverTimezone=GMT%2B8&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: fuck3148481
#日志级别
logging:
  level:
    com:
      longder: DEBUG
#服务器端口
server:
  port: 5188
