#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plant_manage?serverTimezone=GMT%2B8&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: fuck3148481
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#日志级别
logging:
  level:
    com:
      longder: DEBUG
#服务器端口
server:
  port: 5188
system:
  baidu:
    api_id: 16337570
    api_key: 4TzDzz7v5SXWNH4tGE7lzmpO
    secret_key: AUelnrENCC0rVRWfnllOqIgSTMBziN89
